name: Bump Version
description: Install dependencies or restore them from cache
inputs:
  bump:
    description: The type of version bump
    required: false
    default: patch
  GH_TOKEN:
    description: GitHub token
    required: true
runs:
  using: composite
  steps:
    - name: Bump version and get tag
      id: new_version
      uses: anothrNick/github-tag-action@1.64.0
      env:
        GITHUB_TOKEN: ${{ inputs.GH_TOKEN }}
        WITH_V: 'true'
        DEFAULT_BUMP: ${{ inputs.bump }}
        DRY_RUN: 'true'
    - name: NPM version
      shell: bash
      run:
        npm version --allow-same-version=true --git-tag-version=false $NEW_TAG
      env:
        NEW_TAG: ${{ steps.new_version.output.new_tag}}
    - name: Commit Package Version
      id: commit
      shell: bash
      run: |
        exit_code=1
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        if [[ -n "$(git status --porcelain package.json)" ]]; then
          git add package.json
          git add package-lock.json
          git commit -m "[ci skip] chore(package.json): update package json"
          exit_code=0
        fi
        echo "exit_code=${exit_code}" >> "$GITHUB_OUTPUT"
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.64.0
      env:
        GITHUB_TOKEN: ${{ inputs.GH_TOKEN }}
        WITH_V: ${{ true }}
        DEFAULT_BUMP: ${{ inputs.bump }}
    - name: Push to protected branch
      uses: CasperWA/push-protected@v2.15.0
      if: steps.commit.outputs.exit_code == 0
      with:
        token: ${{ inputs.GH_TOKEN }}
        branch: main
        force: true
        tags: true
        unprotect_reviews: true
