name: Check PR title

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  conventional-title:
    runs-on: ubuntu-latest
    if:
      ${{ github.actor != 'dependabot[bot]' && github.actor !=
      'dependabot-preview[bot]' }}
    permissions:
      statuses: write
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
