# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tag on Merge

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  # push:
  #   branches:
  #     - main

env:
  CI: true

permissions: write-all

jobs:
  version_tag:
    if: github.event.pull_request.merged == true
    strategy:
      matrix:
        node-version:
          - 20.7.0
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-tags: true
      - name: Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Bump version
        uses: ./.github/actions/bump-version
        with:
          bump: |
            ${{
              contains(github.event.pull_request.labels.*.name, 'major') && 'major'
              || contains(github.event.pull_request.labels.*.name, 'minor') && 'minor'
              || 'patch'
            }}
