# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tag on Merge

on:
  pull_request:
    types:
      - closed
    branches:
      - main

env:
  CI: true

permissions: write-all

jobs:
  build:
    if: github.event.pull_request.merged == true
    strategy:
      matrix:
        node-version:
          - 20.7.0
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'
          fetch-tags: true
      - name: Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: minor
          DRY_RUN: true
      - run:
          npm version --allow-same-version=true --git-tag-version=false ${{
          steps.tag.outputs.new_tag }}
      - name: Commit Package Version
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -n "$(git status --porcelain package.json)" ]; then
            git add package.json
            git add package-lock.json
            git commit -m "[ci skip] chore(package.json): update package json"
            echo exit_code=0 >> $GITHUB_OUTPUT
          else
            echo exit_code=1 >> $GITHUB_OUTPUT
          fi
      - name: Push to protected branch
        uses: CasperWA/push-protected@v2.15.0
        if: steps.commit.outputs.exit_code == 0
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: main
          force: true
          unprotect_reviews: true
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: minor
          DRY_RUN: true
